name: Deploy Shopify Theme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build theme assets
        run: npm run build

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy to Shopify
        run: |
          shopify theme push \
            --store nightshift-dev.myshopify.com \
            --unpublished --json --publish \
            --theme "Nightshift-${{ github.sha }}" \
            --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
